Fixed typos
Pomax/pomax.github.io pull request #4
Opened 2016-10-27 04:14 UTC by nayuki

I enjoyed reading the fine articles on your site. Thank you for your hard work.

2018-12-18 20:30 UTC, nayuki commented
Hello, any interest in these changes?

2018-12-19 00:31 UTC, Pomax commented
Sorry, apparently gh never bothered to show me this issue existed. typo fixes are already appreciated!

2018-12-19 00:38 UTC, Pomax requested changes
nice, just one request.

2018-12-19 00:38 UTC, Pomax commented on gh-weblog-2/content/posts/markdown/2014-09-20-01-21-59.md
> +You run an open source project, and I have a meaningful contribution for you. I'd love to submit it, but now you're asking me for my personal information, without ever having shown that you can be tr
I think I'd like to keep this as just CLA. If that raises questions, and someone has to google it, that's the kind of exercise that has meaning for the person doing the looking-up.

2018-12-19 01:34 UTC, nayuki commented
Thanks for responding! I leave the changes in your hands now - you can do anything you like. I consider my work to be done.

2018-12-19 16:33 UTC, Pomax approved these changes

2018-12-19 16:33 UTC, Pomax commented
thanks for the fixes!

2018-12-19 16:33 UTC, merged